import PDFDocument from 'pdfkit';
import { formatMoney, formatDateTime } from './invoice-format';

export interface InvoiceData {
  challanNumber: string;
  status: string;
  totalQuantity: number;
  createdAt: string;
  customer: {
    name: string;
    businessName: string;
    mobile: string;
    email: string;
    address: string;
    gstNumber: string | null;
  };
  creator: { name: string; role: string };
  items: {
    name: string;
    sku: string;
    price: number;
    quantity: number;
  }[];
  productSnapshot?: any[];
}

const COMPANY = {
  name: 'Flux Wholesale Distributors',
  tagline: 'Electrical & Lighting Supplies',
  address: 'Plot 42, Industrial Area Phase-II, Pune, Maharashtra 411019',
  gst: 'GSTIN: 27ABCDE1234F1Z5',
};

const PAGE_WIDTH = 595.28;
const MARGIN = 48;
const RIGHT_EDGE = PAGE_WIDTH - MARGIN;
const LEFT_WIDTH = 340;
const RIGHT_X = 420;
const RIGHT_WIDTH = RIGHT_EDGE - RIGHT_X;

function wrapText(doc: PDFKit.PDFDocument, text: string, x: number, y: number, width: number, size: number): number {
  doc.text(text, x, y, { width, lineBreak: true });
  return doc.heightOfString(text, { width });
}

export async function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4' });
  const chunks: Buffer[] = [];

  return new Promise((resolve, reject) => {
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header band
    doc.rect(0, 0, doc.page.width, 110).fill('#1e3a8a');
    doc
      .fill('#ffffff')
      .fontSize(20)
      .font('Helvetica-Bold')
      .text(COMPANY.name, MARGIN, 28, { width: LEFT_WIDTH });
    doc
      .fontSize(10)
      .font('Helvetica')
      .text(COMPANY.tagline, MARGIN, 56);
    doc
      .fontSize(8)
      .text(COMPANY.address, MARGIN, 74, { width: LEFT_WIDTH })
      .text(COMPANY.gst, MARGIN, 86, { width: LEFT_WIDTH });

    const titleText = data.status === 'DRAFT' ? 'PROFORMA INVOICE' : 'SALES INVOICE';
    doc.fill('#ffffff').font('Helvetica-Bold');
    let titleSize = 15;
    doc.fontSize(titleSize);
    while (titleSize > 9 && doc.widthOfString(titleText) > RIGHT_WIDTH) {
      titleSize -= 1;
      doc.fontSize(titleSize);
    }
    doc.text(titleText, RIGHT_X, 30, { width: RIGHT_WIDTH, align: 'right', lineBreak: false });
    doc
      .fontSize(9)
      .font('Helvetica')
      .text(data.challanNumber, RIGHT_X, 52, { width: RIGHT_WIDTH, align: 'right' })
      .text(`Date: ${formatDateTime(data.createdAt)}`, RIGHT_X, 66, { width: RIGHT_WIDTH, align: 'right' });

    // Bill To
    const top = 128;
    doc.fill('#111827').fontSize(11).font('Helvetica-Bold').text('Bill To', MARGIN, top);
    let by = top + 20;
    doc.fill('#374151').fontSize(10).font('Helvetica');
    by += wrapText(doc, data.customer.name, MARGIN, by, LEFT_WIDTH, 10) + 3;
    if (data.customer.businessName) {
      by += wrapText(doc, data.customer.businessName, MARGIN, by, LEFT_WIDTH, 10) + 3;
    }
    by += wrapText(doc, data.customer.mobile, MARGIN, by, LEFT_WIDTH, 10) + 1;
    by += wrapText(doc, data.customer.email, MARGIN, by, LEFT_WIDTH, 10) + 1;
    if (data.customer.address) {
      by += wrapText(doc, data.customer.address, MARGIN, by, LEFT_WIDTH, 10) + 1;
    }
    if (data.customer.gstNumber) {
      by += wrapText(doc, `GSTIN: ${data.customer.gstNumber}`, MARGIN, by, LEFT_WIDTH, 10) + 1;
    }

    const genText = `Generated by: ${data.creator.name} (${data.creator.role})`;
    const genY = top + 20;
    doc
      .fill('#374151')
      .fontSize(9)
      .text(genText, RIGHT_X, genY, { width: RIGHT_WIDTH, align: 'right' });
    const genH = doc.heightOfString(genText, { width: RIGHT_WIDTH });
    doc.text(`Status: ${data.status}`, RIGHT_X, genY + genH + 4, { width: RIGHT_WIDTH, align: 'right' });

    // Items table
    const tableTop = Math.max(by + 10, top + 118);
    let y = tableTop;
    doc.rect(MARGIN, y - 6, RIGHT_EDGE - MARGIN, 22).fill('#f3f4f6');
    doc
      .fill('#111827')
      .fontSize(9)
      .font('Helvetica-Bold');
    doc.text('#', 52, y);
    doc.text('Product', 76, y);
    doc.text('SKU', 260, y);
    doc.text('Unit Price', 330, y, { width: 60, align: 'right' });
    doc.text('Qty', 400, y, { width: 40, align: 'right' });
    doc.text('Amount', 450, y, { width: 97, align: 'right' });

    y += 22;
    data.items.forEach((item, idx) => {
      if (y > 700) {
        doc.addPage();
        y = 60;
        doc.rect(MARGIN, y - 6, RIGHT_EDGE - MARGIN, 22).fill('#f3f4f6');
        doc
          .fill('#111827')
          .fontSize(9)
          .font('Helvetica-Bold');
        doc.text('#', 52, y);
        doc.text('Product', 76, y);
        doc.text('SKU', 260, y);
        doc.text('Unit Price', 330, y, { width: 60, align: 'right' });
        doc.text('Qty', 400, y, { width: 40, align: 'right' });
        doc.text('Amount', 450, y, { width: 97, align: 'right' });
        y += 22;
      }
      if (idx % 2 === 0) {
        doc.rect(MARGIN, y - 6, RIGHT_EDGE - MARGIN, 20).fill('#fafafa');
      }
      doc
        .fill('#374151')
        .fontSize(9)
        .font('Helvetica');
      doc.text(String(idx + 1), 52, y);
      doc.text(item.name, 76, y, { width: 180 });
      doc.text(item.sku, 260, y, { width: 60 });
      doc.text(formatMoney(item.price), 330, y, { width: 60, align: 'right' });
      doc.text(String(item.quantity), 400, y, { width: 40, align: 'right' });
      doc.text(formatMoney(item.price * item.quantity), 450, y, { width: 97, align: 'right' });
      y += 20;
    });

    // Totals
    const totalAmount = data.items.reduce((s, i) => s + i.price * i.quantity, 0);
    y += 12;
    doc.rect(RIGHT_X, y - 6, RIGHT_WIDTH, 28).fill('#1e3a8a');
    doc
      .fill('#ffffff')
      .fontSize(9)
      .font('Helvetica-Bold')
      .text('Total Quantity', RIGHT_X + 6, y, { width: 70 });
    doc.text(String(data.totalQuantity), RIGHT_X + RIGHT_WIDTH - 60, y, { width: 54, align: 'right' });
    doc
      .fontSize(11)
      .text(formatMoney(totalAmount), RIGHT_X + 6, y + 13, { width: RIGHT_WIDTH - 12, align: 'right' });

    y += 50;
    doc
      .fill('#6b7280')
      .fontSize(8)
      .font('Helvetica')
      .text(
        'This is a system-generated document and does not require a physical signature.',
        MARGIN,
        doc.page.height - 60
      )
      .text('Amounts in INR. Subject to Pune jurisdiction.', MARGIN, doc.page.height - 48);

    doc.end();
  });
}
