import PDFDocument from 'pdfkit';
import { formatMoney, formatDateTime } from './invoice-format';

export interface InvoiceData {
  challanNumber: string;
  status: string;
  totalQuantity: number;
  createdAt: string;
  customer: {
    name: string;
    businessName: string;
    mobile: string;
    email: string;
    address: string;
    gstNumber: string | null;
  };
  creator: { name: string; role: string };
  items: {
    name: string;
    sku: string;
    price: number;
    quantity: number;
  }[];
  productSnapshot?: any[];
}

const COMPANY = {
  name: 'Flux Wholesale Distributors',
  tagline: 'Electrical & Lighting Supplies',
  address: 'Plot 42, Industrial Area Phase-II, Pune, Maharashtra 411019',
  gst: 'GSTIN: 27ABCDE1234F1Z5',
};

export async function generateInvoicePdf(data: InvoiceData): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 48, size: 'A4' });
  const chunks: Buffer[] = [];

  return new Promise((resolve, reject) => {
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header band
    doc.rect(0, 0, doc.page.width, 110).fill('#1e3a8a');
    doc
      .fill('#ffffff')
      .fontSize(22)
      .font('Helvetica-Bold')
      .text(COMPANY.name, 48, 28);
    doc
      .fontSize(10)
      .font('Helvetica')
      .text(COMPANY.tagline, 48, 58);
    doc
      .fontSize(8)
      .text(COMPANY.address, 48, 76)
      .text(COMPANY.gst, 48, 88);

    doc
      .fill('#ffffff')
      .fontSize(18)
      .font('Helvetica-Bold')
      .text(data.status === 'DRAFT' ? 'PROFORMA INVOICE' : 'SALES INVOICE', 430, 32, { width: 120, align: 'right' });
    doc
      .fontSize(9)
      .font('Helvetica')
      .text(data.challanNumber, 430, 62, { width: 120, align: 'right' })
      .text(`Date: ${formatDateTime(data.createdAt)}`, 430, 76, { width: 120, align: 'right' });

    // Bill To
    const top = 128;
    doc.fill('#111827').fontSize(11).font('Helvetica-Bold').text('Bill To');
    doc
      .fill('#374151')
      .fontSize(10)
      .font('Helvetica')
      .text(data.customer.name, 48, top + 18);
    if (data.customer.businessName) {
      doc.text(data.customer.businessName, 48, top + 32);
    }
    doc
      .text(data.customer.mobile, 48, top + (data.customer.businessName ? 46 : 32))
      .text(data.customer.email, 48, top + (data.customer.businessName ? 60 : 46));
    if (data.customer.address) {
      doc.text(data.customer.address, 48, top + (data.customer.businessName ? 74 : 60));
    }
    if (data.customer.gstNumber) {
      doc.text(`GSTIN: ${data.customer.gstNumber}`, 48, top + (data.customer.businessName ? 90 : 76));
    }

    doc
      .fill('#374151')
      .fontSize(9)
      .text(`Generated by: ${data.creator.name} (${data.creator.role})`, 430, top + 18, { width: 120, align: 'right' })
      .text(`Status: ${data.status}`, 430, top + 34, { width: 120, align: 'right' });

    // Items table
    let y = top + (data.customer.gstNumber ? 118 : 104);
    doc.rect(48, y - 6, 510, 22).fill('#f3f4f6');
    doc
      .fill('#111827')
      .fontSize(9)
      .font('Helvetica-Bold');
    doc.text('#', 52, y);
    doc.text('Product', 76, y);
    doc.text('SKU', 290, y);
    doc.text('Unit Price', 360, y);
    doc.text('Qty', 428, y, { width: 40, align: 'right' });
    doc.text('Amount', 480, y, { width: 74, align: 'right' });

    y += 22;
    data.items.forEach((item, idx) => {
      if (y > 700) {
        doc.addPage();
        y = 60;
      }
      if (idx % 2 === 0) {
        doc.rect(48, y - 6, 510, 20).fill('#fafafa');
      }
      doc
        .fill('#374151')
        .fontSize(9)
        .font('Helvetica');
      doc.text(String(idx + 1), 52, y);
      doc.text(item.name, 76, y, { width: 200 });
      doc.text(item.sku, 290, y, { width: 60 });
      doc.text(formatMoney(item.price), 360, y, { width: 60, align: 'right' });
      doc.text(String(item.quantity), 428, y, { width: 40, align: 'right' });
      doc.text(formatMoney(item.price * item.quantity), 480, y, { width: 74, align: 'right' });
      y += 20;
    });

    // Totals
    const totalAmount = data.items.reduce((s, i) => s + i.price * i.quantity, 0);
    y += 12;
    doc.rect(430, y - 6, 128, 26).fill('#1e3a8a');
    doc
      .fill('#ffffff')
      .fontSize(9)
      .font('Helvetica-Bold')
      .text('Total Quantity', 436, y, { width: 58 });
    doc.text(String(data.totalQuantity), 492, y, { width: 60, align: 'right' });
    doc
      .fontSize(11)
      .text(formatMoney(totalAmount), 436, y + 12, { width: 116, align: 'right' });

    y += 46;
    doc
      .fill('#6b7280')
      .fontSize(8)
      .font('Helvetica')
      .text(
        'This is a system-generated document and does not require a physical signature.',
        48,
        doc.page.height - 60
      )
      .text('Amounts in INR. Subject to Pune jurisdiction.', 48, doc.page.height - 48);

    doc.end();
  });
}
